nama = input("nama kamu siapa: ")
kelas = input("kamu kelas berapa: ")
umur = input("umur kamu berapa: ")
hobi = input("hobi kamu apa: ")
film = input("movie kesukaanmu apa: ")
sekolah = input("sekolahmu dimana: ")
jurusan = input("apa jurusanmu: ")
mapel = input("mapel kesukaanmu apa: ")
game = input("game kesukaan mu apa: ")
print("nama saya adalah" , nama, "saya berada dikelas" , kelas, "saya mengambil jurusan" , jurusan, "hobi ku adalah bermain" , hobi, "mata pelajaran kesukaan saya adalah" , mapel)
